version: "3"
services:
  api:
    build: ./backend
    depends_on:
      - postgres-db
    ports:
    - 8000:8000
    volumes:
    - ./backend:/usr/src/backend_app:ro
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_HOSTNAME=postgres-db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - REFRESH_TOKEN_EXPIRE_MINUTES=${REFRESH_TOKEN_EXPIRE_MINUTES}
  postgres-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
    - postgres-db:/var/lib/postgresql/data
    ports:
    - 5434:5432

  client:
    build: ./frontend
    depends_on:
      - api
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/frontend_app

volumes:
  postgres-db: